# Checkout Address Autocomplete Extension
api_version = "2025-10"

[[extensions]]

uid = "5096b0ad-13e0-e3ae-91d3-2536e4353b36062bdb44"

type = "ui_extension"
name = "google-address-autocomplete"
handle = "google-address-autocomplete"
metafields = []

[[extensions.targeting]]
target = "purchase.address-autocomplete.suggest"
module = "./src/index.js"
access = "public"

[extensions.capabilities]
network_access = true

[extensions.settings]

[[extensions.settings.fields]]
key = "google_maps_api_key"
type = "single_line_text_field"
name = "Google Maps API Key"
description = "Enter your Google Maps API key."
validations = []

[[extensions.settings.fields]]
key = "backend_url"
type = "single_line_text_field"
name = "Backend URL (Optional)"
description = "Optional backend proxy URL."
validations = []
